sources:
  - name: jaffle_shop
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        columns:
          - name: id
            data_tests:
              - unique
              - not_null
      - name: orders
        columns:
          - name: id
            data_tests:
              - unique
<<<<<<< HEAD
              - not_null
=======
              - not_null
>>>>>>> 53a8a4684d1a8eedf288d32244b9d744eeb74b58
